spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wx_detai?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 'root'

  jpa:
#    database: mysql
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

# 关闭springBoot的安全验证
security:
  basic:
    enabled: false

FTP:
  ADDRESS: 120.234.32.67
  PORT: 52020
  USERNAME: gps_lhk
  PASSWORD: lhk#783
  BASEPATH: /temp/images