package cn.com.detail.wx.utils;

public interface ErrorCode {

    short OK = 0;

    short UNKNOWN_ERROR = 1000;
    short INTERNAL_SERVER_ERROR = 1001;
    short ENTITY_NOT_FOUND = 1002;
    short DELETE_FAILED = 1003;
    short NON_SELECTION = 1004;
    short JPA_DATA_ACCESS_ERROR = 1005;
    short APPROVAL_EXISTED = 1006;
    short NECESSARY_ENTITY_IS_NOT_SAVED = 1007;
    short DELETION_RESTRICTED = 1008;
    short DATA_SUBMIT_FAILED = 1009;
    short REQUIRED_PARAMETER_MISSING = 1010;
    short VALIDATION_ERROR = 1012;
    short ENTITY_IS_REFERENCED = 1013;
    short JS_SCRIPT_EXECUTION_ERROR = 1014;
    short ILLEGAL_DATA = 1015;
    short SET_STATUS_FAILED = 1016;
    short RECOVER_STATEFUL_CONTEXT_FAILED = 1017;
    short PARAM_IS_ERROR = 1019;
    short ATTRIBUTE_CANNOT_BE_NULL = 1020;
    short ENTITY_ALREADY_EXIST = 1021;
    short GET_SHARED_OBJECT_FAILED = 1022;
    short FLOW_ERROR = 1023;
    short SAVE_ENTITY_FAILED = 1024;
    short AUTHORIZATION_REQUIRED = 1025;
    short INVALID_JPA_MAPPING = 1026;
    short DUPLICATED_CODE = 1027;
    short DASHBOARD_SQL_EXECUTION_ERROR = 1028;
    short PROPERTY_INDEX_QUERY_SQL_EXECUTION_ERROR = 1029;
    short SEND_PIWIK_STATISTIC_FAILED = 1030;
    short INVALID_OPERATION = 1031;

    //grid_column_prefer
    short GRID_COLUMN_PREFER_QUERY_ERROR = 1031;
    short GRID_COLUMN_PREFER_UPDATE_ERROR = 1032;
    short GRID_COLUMN_PREFER_REMOVE_ERROR = 1033;

    short EXPORT_EXCEL_OVER_MAX_NUMBER = 1034;

    short CHANGE_PASSWORD_FAILED = 2001;
    short SAVE_ACCOUNT_FAILED = 2002;
    short NO_ROLE_AVAILABLE = 2003;
    short NEED_CHANGE_PASSWORD_NOW = 2004;

    short MACHINE_SCHEDULE_SETTING_NOT_FOUND = 3001;
    short MOLD_TYPE_IS_REFERENCED = 3002;
    short MOLD_IS_REFERENCED = 3003;
    short PRODUCT_IS_PRODUCING = 3004;

    short PROCEDURE_PRODUCT_NOT_SYNCHRONIZED = 4001;
    short PROCEDURE_PRODUCT_TYPE_NOT_SET = 4002;
    short PROCEDURE_TOO_MUCH_ORDER_COUNT = 4003;
    short COMPLETION_FORM_IS_SAVED = 4004;
    short PROCESSING_MOVEMENT_IS_NOT_FROM_SAME_SOURCE = 4005;
    short DETAIL_SUM_EXCEED = 4006;
    short ROOT_COMPLETION_COUNT_MUST_NOT_BE_ZERO = 4007;
    short PROCESSING_MOVEMENT_IS_SAVED = 4008;
    short COMPLETION_DETAIL_MUST_NOT_BE_MODIFIED = 4009;
    short COMPLETION_FORM_IS_NOT_SAVED = 4010;
    short CANNOT_EDIT_EFFECTIVE_RECORD = 4011;
    short COMPLETION_COUNT_EXCEED = 4012;
    short SPLIT_COUNT_MORE_THAN_REMAIN_COUNT = 4013;
    short GENERATE_PDF_FAILED = 4014;
    short INVALID_MOVEMENT_COUNT = 4015;
    short MOVEMENT_FOR_ROOT_TASK = 4016;
    short SOURCE_TARGET_MACHINE_ARE_SAME = 4017;
    short SCHEDULING_ORDER_CANNOT_SWITCH_MACHINE = 4018;
    short COMPLETION_FORM_IS_NOT_LAST_NODE = 4019;
    short EDIT_PRODUCT_NOT_EXIST = 4020;
    short NON_SUPPORTED_WORK_ORDER_TYPE = 4021;
    short DUPLICATE_PRODUCING = 4022;
    short COMPLETION_FORM_IS_NOT_ALLOW_TO_DELETE = 4023;
    short WORK_ORDER_CAN_NOT_BE_RESCHEDULED = 4024;

    short TRY_TO_DELETE_SPECIAL_TABLE = 5001;
    short LEAGUE_ITEM_IS_NOT_EDITABLE = 5002;
    short SERIAL_NUM_OF_PRODUCT_IS_NOT_SET = 5003;
    short PENDING_APPROVAL = 5004;
    short DELETE_STRUCTURE_FAILED = 5005;
    short STRUCTURE_ENTRY_IS_EXISTED = 5006;
    short STRUCTURE_BOM_ENTRY_IS_EXISTED = 5007;
    short DELETE_LEAGUE_CATALOG_FAILED = 5008;
    short SAVE_TEMPLATE_FAILED = 5009;
    short SAVE_STRUCTURE_FAILED = 5010;
    short MISSING_EMPTY_DETAIL_LEAGUE = 5011;
    short DELETE_LEAGUE_DETAIL_FAILED = 5012;
    short SAVE_PRODUCT_FAILED = 5013;
    short SAVE_STRUCTURE_BOM_FAILED = 5014;
    short ASSOCIATE_PRODUCT_EXISTED = 5015;
    short SAVE_PRODUCT_BOM_FAILED = 5016;
    short SAVE_STRUCTURE_BOM_ASSOCIATION_FAILED = 5017;
    short STRUCTURE_BOM_ENTRY_IS_NOT_SET = 5018;
    short PRODUCT_NOT_SET = 5019;
    short REMOVE_STRUCTURE_BOM_ASSOCIATION_FAILED = 5020;
    short IMPORTED_PRODUCT_CODE_NOT_BIND_YET = 5021;
    short DELETE_STRUCTURE_BOM_FAILED = 5022;
    short PRODUCT_BOM_ENTRY_NOT_SET_YET = 5023;
    short PRODUCT_BOM_ENTRY_IS_EXISTED = 5024;
    short INVALID_SPEC_RULE = 5025;
    short GENERATE_BOM_FAILED = 5026;
    short FORMALIZE_FAILED = 5027;
    short STRUCTURE_BOM_PRODUCT_BOM_NOT_MATCHED = 5028;
    short HESITATE_FALIED = 5029;
    short INVALID_NG_PRODUCT = 5030;
    short INVALID_NP_STRUCTURE = 5031;
    short INVALID_NP_DEVELOPMENT_TASK = 5032;

    short END_PRODUCT_VALIDATE_ERROR = 6001;
    short END_PRODUCT_CODE_EXISTED = 6002;
    short PRODUCT_ORDER_PENDING = 6003; //订单已下单待审批
    short PRODUCT_ORDER_DEAL = 6004;    //订单已正式下单
    short SAMPLE_NOT_NEED = 6005;       //成品不需要样品
    short SAMPLE_ORDER_ENDING = 6006;
    short PRODUCT_ORDER_PASS_FAIL = 6007;
    short SAMPLE_NOT_CONFIRM = 6008;
    short ENDPRODUCT_NOT_FINISH = 6009;
    short PRODUCT_CHECK_LEAGUE_INACCORDANCE = 6010;
    short STENCIL_BIND_FAIL = 6011;
    short STENCIL_BIND_CONFLICT = 6012;
    short PRODUCT_ORDER_UNFINISHED = 6013;
    short EMPLOYEE_NO_ACCOUNT = 6014;
    short IMPORTED_END_PRODUCT_CAN_NOT_TURNED = 6015; //历史订单成品翻单校验失败
    short POPROPERTY_FIELD_NAME_DUPLICATED = 6016;
    short SAMPLE_ORDER_UNFINISHED = 6017;
    short PO_END_PRODUCT_NOT_READY_FOR_PRODUCTION = 6018;
    short END_PRODUCTS_IS_NOT_EMPTY = 6019;
    short MATCH_COLOUR_TASK_DATA_INCOMPLETE = 6020;
    short COLOUR_SAVE_FAILED = 6021;
    short COLOUR_VALIDATION_FAILED = 6022;
    short COLOUR_FORMULA_DUPLICATE = 6023; //色号配方的 供应商与原材料唯一性校验失败
    short DELETE_END_PRODUCT_FAILED = 6024;
    short COLOUR_FORMULA_NOT_CHANGED = 6025;

    short INV_ITEM_DOES_NOT_EXIST = 7001;
    short INV_NOT_ENOUGH_STOCK_COUNT = 7002;
    short INV_REVISED_ITEM_CODE_NOT_IN_STOCK = 7003;
    short INV_NEGATIVE_STOCK_OP_COUNT = 7004;
    short INV_DELETE_CATEGORY_NOT_ALLOW = 7005;
    short INV_SHEET_IS_APPROVED = 7006;
    short EXISTED_ON_GOING_WORKORDER_COUNT = 7007;
    short PRODUCT_BE_LOCKED = 7008;

    short LRP_NO_CONFIRMED_END_PRODUCT = 8001;
    short NG_APPROVE_PRODUCT_PHOTO_JUDGE = 8002;
}
