package cn.com.detail.wx.utils;

public interface ErrorCode {

    short OK = 0;

    short UNKNOWN_ERROR = 1000;
    short INTERNAL_SERVER_ERROR = 1001;
    short ENTITY_NOT_FOUND = 1002;
    short DELETE_FAILED = 1003;
    short NON_SELECTION = 1004;
    short JPA_DATA_ACCESS_ERROR = 1005;
    short APPROVAL_EXISTED = 1006;
    short NECESSARY_ENTITY_IS_NOT_SAVED = 1007;
    short DELETION_RESTRICTED = 1008;
    short DATA_SUBMIT_FAILED = 1009;
    short REQUIRED_PARAMETER_MISSING = 1010;
    short VALIDATION_ERROR = 1012;
    short ENTITY_IS_REFERENCED = 1013;
    short JS_SCRIPT_EXECUTION_ERROR = 1014;
    short ILLEGAL_DATA = 1015;
    short SET_STATUS_FAILED = 1016;
    short RECOVER_STATEFUL_CONTEXT_FAILED = 1017;
    short PARAM_IS_ERROR = 1019;
    short ATTRIBUTE_CANNOT_BE_NULL = 1020;
    short ENTITY_ALREADY_EXIST = 1021;
    short GET_SHARED_OBJECT_FAILED = 1022;
    short FLOW_ERROR = 1023;
    short SAVE_ENTITY_FAILED = 1024;
    short AUTHORIZATION_REQUIRED = 1025;
    short INVALID_JPA_MAPPING = 1026;
    short DUPLICATED_CODE = 1027;
    short DASHBOARD_SQL_EXECUTION_ERROR = 1028;
    short PROPERTY_INDEX_QUERY_SQL_EXECUTION_ERROR = 1029;
    short SEND_PIWIK_STATISTIC_FAILED = 1030;

    //grid_column_prefer
    short GRID_COLUMN_PREFER_QUERY_ERROR = 1031;
    short GRID_COLUMN_PREFER_UPDATE_ERROR = 1032;
    short GRID_COLUMN_PREFER_REMOVE_ERROR = 1033;

    short CHANGE_PASSWORD_FAILED = 2001;
    short SAVE_ACCOUNT_FAILED = 2002;
    short NO_ROLE_AVAILABLE = 2003;
    short NEED_CHANGE_PASSWORD_NOW = 2004;

    short MACHINE_SCHEDULE_SETTING_NOT_FOUND = 3001;
    short MOLD_TYPE_IS_REFERENCED = 3002;
    short MOLD_IS_REFERENCED = 3003;
    short PRODUCT_IS_PRODUCING = 3004;

}
